version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      ENABLE_RCON: "true"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped

  webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MC_HOST=minecraft
      - MC_PORT=25565
      - RCON_PORT=25575
      - RCON_PASSWORD=${RCON_PASSWORD}
    depends_on:
      - minecraft
    restart: unless-stopped
